### PR TITLE
Made newTerm operation idempotent instead of returning AlreadyFenced error

### LINKED ISSUE #596: bug: panic: runtime error: invalid memory address or nil pointer dereference
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x192d87d]

goroutine 104 [running]:
github.com/streamnative/oxia/coordinator/impl.(*shardController).internalNewTermAndAddFollower(0xc0001d0b00, {0x2534a60?, 0xc000af2730?}, {{0xc00011dea0, 0x45}, {0xc000516cc0, 0x2f}}, 0xc0005d73b0)
	/src/oxia/coordinator/impl/shard_controller.go:513 +0xfd
github.com/streamnative/oxia/coordinator/impl.(*shardController).run(0xc0001d0b00)
	/src/oxia/coordinator/impl/shard_controller.go:202 +0x545
github.com/streamnative/oxia/common.DoWithLabels.func1({0x2534a28?, 0xc00077f890?})
	/src/oxia/common/pprof.go:46 +0x13
runtime/pprof.Do({0x2534a60?, 0xc000139950?}, {{0xc00068eb40?, 0x0?, 0x0?}}, 0xc000484f30)
	/usr/local/go/src/runtime/pprof/runtime.go:51 +0x8c
github.com/streamnative/oxia/common.DoWithLabels({0x2534a60, 0xc000139950}, 0xc000644210, 0xc00063e1d0)
	/src/oxia/common/pprof.go:42 +0x34d
created by github.com/streamnative/oxia/coordinator/impl.NewShardController in goroutine 1
	/src/oxia/coordinator/impl/shard_controller.go:150 +0xba5
```

### PR DESCRIPTION
**Pull request by merlimat**
Fixes #596

### CODE REVIEW

File: server/follower_controller.go [hunk 1]
```diff
@@ -267,16 +267,6 @@ func (fc *followerController) NewTerm(req *proto.NewTermRequest) (*proto.NewTerm
 			slog.Int64("new-term", req.Term),
 		)
 		return nil, common.ErrorInvalidTerm
-	} else if req.Term == fc.term && fc.status != proto.ServingStatus_FENCED {
```
Comment (mattisonchao) [inline server/follower_controller.go:270]: If they are same term, how about return the `lastEntryId, err := getLastEntryIdInWal(fc.wal)` directly?

**Review by mattisonchao — APPROVED** [review]
LGTM, and I think we can also make the `addFollower` as idempotent to avoid extra error handling.
